### ISSUE TITLE
Mlem should provide inbox notifications

### ISSUE THREAD

**Issue by BrooklynMan** [buresdv/Mlem#82] opened 2023-06-10 19:00 UTC
## Introduction
Apps that provide service which receive messages and new comment replies should provide users with notifications

## Requirements
Mlem should provide notifications of receipt of messages and new comment replies to inbox.

## Discussion
Please add the option for the app to provide notifications of inbox messages and new comment replies, possibly with options for alert tones.

## What I Need
provide notifications for inbox messages and new comment replies

**Comment by ShadowJonathan** [comment] 2023-06-10 19:06
Duplicate of https://github.com/buresdv/Mlem/issues/45

**Closed** 2023-06-11 10:56 UTC
Labels: enhancement, "Like Apollo"
